# Generated by Django 3.2.9 on 2021-11-08 08:37

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='profiles/default_rWpNfNs.jpg', upload_to='profiles'),
        ),
    ]
